let chaptersEN = [
    "Dummy",
    "A Stolen Skill",
    "Pirate Revolt",
    "Eliza s Rage",
    "Scorpion Poison",
    "A New Friend",
    "Horntail s Gem",
    "The Mechanics",
    "Sunken Ruins",
    "Farewell Chise",
    "Final Battle",
    "Epilogue"
]

let mainQuestsEN = [
    "Late for Training 1",
    "Late for Training 2",
    "Stolen Secret",
    "Herb Town’s Great Doctor",
    "Lower The Drawbridge",
    "Pirate Escape",
    "Herb Town’s Great Doctor",
    "Spiruna in Orbis",
    "Anger of Eliza 1",
    "Anger of Eliza 2",
    "Another Eliza",
    "Going Back to Spiruna",
    "Holy Water of Ariant",
    "Polluted Holy Water",
    "Eternal Flask",
    "Zenumist Society 1",
    "Zenumist Society 2",
    "Look for Yulete’s House",
    "Yulete Disappears",
    "Alcadno Society",
    "Where is Frankenroid?",
    "Holy Water of Ariant",
    "Toward Minar Forest",
    "Where is Horntail?",
    "To Horntail’s Nest",
    "A Transformation Potion",
    "Encounter Horntail",
    "Mysterious Return Stone",
    "Help the Kidnapped Child",
    "With Duke",
    "Misunderstood Conversation",
    "Let’s Return To Orbis",
    "Looking For The Ruins",
    "People from the Opposite Side",
    "The Shining Stone",
    "To Edelstein",
    "Protect the Generator",
    "I Won’t Permit It",
    "Pursue Morgan 1",
    "Pursue Morgan 2",
    "Pursue Morgan 3",
    "Entrance Of The Ruins",
    "True Battle Mage"
]

/*
let subQuestsEN = {
    : "Lost Earring",
    : "Cause Of The Trouble",
    : "Missing Hella",
    : "Hella Is Safe",
    : "Lonely Moppie",
    : "Nependeath’s Remedy",
    : "Antidote Needed",
    : "Red Scorpions’ Treasure",
    : "A Pirate In The Desert",
    : "The Need For Life Alchemy",
    : "Problems With Life Alchemy",
    : "Lloyd’s Research on Keeny",
    : "Too Many Mosquitoes",
    : "A Pill Is Necessary",
    : "Former Village Chief’s Testament",
    : "Monster In The Forest",
    : "Grandfather’s Fishing Rod",
    : "Tae Gong’s Love For His Wife",
    : "Menace of Shaqra",
    : "Cease Living",
    : "Broken Telephone Booth",
    : "No Content",
    : "No Content",
    : "Bring Poopa Egg 1",
    : "Bring Poopa Egg 2",
    : "Bring Poopa Egg 3"
}

let mainQuestsJP = [
    "訓練時間に遅れちゃう１",
    "訓練時間に遅れちゃう２",
    "盗まれた秘技",
    "白草村の名医",
    "跳ね橋を降ろさなくっちゃ",
    "海賊船脱出",
    "白草村の名医",
    "オルビスのスピルナ",
    "エリジャーの怒り１",
    "エリジャーの怒り２",
    "もう一匹のエリジャー",
    "再びスピルナのもとへ",
    "アリアントの聖水",
    "汚染された聖水",
    "エターナルフラスコ",
    "ジェニミスト協会１",
    "ジェニミスト協会２",
    "ユレテの家探し",
    "消えたユレテ",
    "アルカドノ協会",
    "フランケンロイドの行方",
    "アリアントの聖水",
    "ミナルの森に向かって",
    "ホーンテイルはどこに？",
    "ホーンテイルの巣へ",
    "変身の秘薬作り",
    "ホーンテイルに会って",
    "神秘的な帰還の石",
    "さらわれた子を助けて",
    "デュークと共に",
    "会話が通じない",
    "オルビスに帰ろう",
    "遺跡を探して",
    "反対側にいる人",
    "輝く石を探そう",
    "エーデルシュタインへ",
    "風力発電機を守って",
    "許さない",
    "モーガンを追って１",
    "モーガンを追って２",
    "モーガンを追って３",
    "遺跡の入口へ",
    "真のバトルメイジ"
]

let subQuestsJP = {
    : "失くしたイヤリング",
    : "故障の原因",
    : "行方不明になったヘラー",
    : "ヘラーの安否を伝える",
    : "寂しそうなボンちゃん",
    : "ネペンデスの秘薬",
    : "解毒剤が必要",
    : "赤サソリ団の宝",
    : "砂漠の海賊",
    : "生命錬金の必要性",
    : "生命錬金の問題点",
    : "キニのロイド研究",
    : "蚊が多すぎる",
    : "毛玉が必要",
    : "先代村長の遺言状",
    : "森の中のモンスター",
    : "漁師爺の釣竿",
    : "漁師爺の妻への愛",
    : "シャクラーの脅威",
    : "絶えゆく命",
    : "故障した電話ボックス",
    : "内容なし",
    : "内容なし",
    : "ﾊﾟﾌｧｰの卵を持ってきて1",
    : "ﾊﾟﾌｧｰの卵を持ってきて2",
    : "ﾊﾟﾌｧｰの卵を持ってきて3"
}*/